# .github/labeler.yml

# CI/CD ile ilgili değişiklikler
ci/cd:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"

# Backend (Frappe / ERPNextKTA app)
backend:
  - changed-files:
      - any-glob-to-any-file:
          - "erpnextkta/**"

# QR Scanner / Frontend tarafı
frontend:
  - changed-files:
      - any-glob-to-any-file:
          - "erpnextkta/public/**"

# Dokümantasyon
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "**/*.md"

# Config / Docker / Deploy
deployment:
  - changed-files:
      - any-glob-to-any-file:
          - "docker/**"
          - "deploy/**"
          - "compose*.yml"
          - "compose/**"
          - "k8s/**"